### ISSUE TITLE
Module build failed: TypeError: has no method 'isAbsolute' at HelperRemap.js:216:17

### ISSUE THREAD

**Issue by robgha01** [brianZeng/babel-plugin-transform-helper#2]
Im using NodeJs 4.7.0 and i get this bellow error message.

```
ERROR in ./App_Plugins/BlueLeet.UComponents/Source/index.ts
Module build failed: TypeError: D:/Workspaces/BlueLeet/BlueLeet.UComponents/BlueLeet.UComponents/App_Plugins/BlueLeet.UComponents/Source/index.ts: Object #<Object> has no method 'isAbsolute'
    at HelperRemap.get (D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-plugin-transform-helper\lib\HelperRemap.js:216:17)
    at PluginPass.pre (D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-plugin-transform-helper\lib\index.js:24:32)
    at File.call (D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-core\lib\transformation\file\index.js:643:18)
    at File.transform (D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-core\lib\transformation\file\index.js:559:12)
    at D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-core\lib\transformation\pipeline.js:50:19
    at File.wrap (D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-core\lib\transformation\file\index.js:579:16)
    at Pipeline.transform (D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-core\lib\transformation\pipeline.js:47:17)
    at transpile (D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (D:\Workspaces\BlueLeet\BlueLeet.UComponents\BlueLeet.UComponents\node_modules\babel-loader\index.js:131:12)
 @ multi main
[20:14:43] Finished 'compile:ts' after 17 s
Process terminated with code 0.
```

**Comment by robgha01** [comment]
downgrading to NodeJs 4.6.0 seams to solve the problem, i guess thay made a breaking change from4.6.0 to 4.7.0. Now i only need to figure out where the tempHelper.js is created... nvm it seams to not copy itself to the output directory i will look into that if its a cuse of this plugin or if gulp is behaving bad.

**Comment by brianZeng** [comment]
`isAbsolute()` is called from node module 'path'. This may be a issue caused by your node environment. Can you try  the latest node version
